package models

type AutoGenerated struct {
	AnalyzeExpenseModelVersion string `json:"AnalyzeExpenseModelVersion"`
	DocumentMetadata           struct {
		Pages int `json:"Pages"`
	} `json:"DocumentMetadata"`
	ExpenseDocuments ExpenseDocuments `json:"ExpenseDocuments"`
	JobStatus        string           `json:"JobStatus"`
	NextToken        interface{}      `json:"NextToken"`
	StatusMessage    interface{}      `json:"StatusMessage"`
	Warnings         interface{}      `json:"Warnings"`
}

type ExpenseDocuments []struct {
	Blocks []struct {
		BlockType   string      `json:"BlockType"`
		ColumnIndex interface{} `json:"ColumnIndex"`
		ColumnSpan  interface{} `json:"ColumnSpan"`
		Confidence  interface{} `json:"Confidence"`
		EntityTypes interface{} `json:"EntityTypes"`
		Geometry    struct {
			BoundingBox struct {
				Height float64 `json:"Height"`
				Left   float64 `json:"Left"`
				Top    float64 `json:"Top"`
				Width  float64 `json:"Width"`
			} `json:"BoundingBox"`
			Polygon []struct {
				X float64 `json:"X"`
				Y float64 `json:"Y"`
			} `json:"Polygon"`
		} `json:"Geometry"`
		Hint               interface{} `json:"Hint"`
		ID                 string      `json:"Id"`
		Page               int         `json:"Page"`
		PageClassification interface{} `json:"PageClassification"`
		Query              interface{} `json:"Query"`
		Relationships      []struct {
			Ids  []string `json:"Ids"`
			Type string   `json:"Type"`
		} `json:"Relationships"`
		RowIndex        interface{} `json:"RowIndex"`
		RowSpan         interface{} `json:"RowSpan"`
		SelectionStatus interface{} `json:"SelectionStatus"`
		Text            interface{} `json:"Text"`
		TextType        interface{} `json:"TextType"`
	} `json:"Blocks"`
	ExpenseIndex   int `json:"ExpenseIndex"`
	LineItemGroups []struct {
		LineItemGroupIndex int `json:"LineItemGroupIndex"`
		LineItems          []struct {
			LineItemExpenseFields []struct {
				Currency        interface{} `json:"Currency"`
				GroupProperties interface{} `json:"GroupProperties"`
				LabelDetection  struct {
					Confidence float64 `json:"Confidence"`
					Geometry   struct {
						BoundingBox struct {
							Height float64 `json:"Height"`
							Left   float64 `json:"Left"`
							Top    float64 `json:"Top"`
							Width  float64 `json:"Width"`
						} `json:"BoundingBox"`
						Polygon []struct {
							X float64 `json:"X"`
							Y float64 `json:"Y"`
						} `json:"Polygon"`
					} `json:"Geometry"`
					Text string `json:"Text"`
				} `json:"LabelDetection"`
				PageNumber int `json:"PageNumber"`
				Type       struct {
					Confidence float64 `json:"Confidence"`
					Text       string  `json:"Text"`
				} `json:"Type"`
				ValueDetection struct {
					Confidence float64 `json:"Confidence"`
					Geometry   struct {
						BoundingBox struct {
							Height float64 `json:"Height"`
							Left   float64 `json:"Left"`
							Top    float64 `json:"Top"`
							Width  float64 `json:"Width"`
						} `json:"BoundingBox"`
						Polygon []struct {
							X float64 `json:"X"`
							Y float64 `json:"Y"`
						} `json:"Polygon"`
					} `json:"Geometry"`
					Text string `json:"Text"`
				} `json:"ValueDetection"`
			} `json:"LineItemExpenseFields"`
		} `json:"LineItems"`
	} `json:"LineItemGroups"`
	SummaryFields []struct {
		Currency        interface{} `json:"Currency"`
		GroupProperties []struct {
			ID    string   `json:"Id"`
			Types []string `json:"Types"`
		} `json:"GroupProperties"`
		LabelDetection struct {
			Confidence float64 `json:"Confidence"`
			Geometry   struct {
				BoundingBox struct {
					Height float64 `json:"Height"`
					Left   float64 `json:"Left"`
					Top    float64 `json:"Top"`
					Width  float64 `json:"Width"`
				} `json:"BoundingBox"`
				Polygon []struct {
					X float64 `json:"X"`
					Y float64 `json:"Y"`
				} `json:"Polygon"`
			} `json:"Geometry"`
			Text string `json:"Text"`
		} `json:"LabelDetection"`
		PageNumber int `json:"PageNumber"`
		Type       struct {
			Confidence float64 `json:"Confidence"`
			Text       string  `json:"Text"`
		} `json:"Type"`
		ValueDetection struct {
			Confidence float64 `json:"Confidence"`
			Geometry   struct {
				BoundingBox struct {
					Height float64 `json:"Height"`
					Left   float64 `json:"Left"`
					Top    float64 `json:"Top"`
					Width  float64 `json:"Width"`
				} `json:"BoundingBox"`
				Polygon []struct {
					X float64 `json:"X"`
					Y float64 `json:"Y"`
				} `json:"Polygon"`
			} `json:"Geometry"`
			Text string `json:"Text"`
		} `json:"ValueDetection"`
	} `json:"SummaryFields"`
}
